### ISSUE TITLE
Calendar button unusable

### ISSUE THREAD

**Issue by LVS04** [WhiteKarma/NalandaERP#11]
When one click on the calendar button of the birth date (Main / General) the image is cutted so impossible to chose the year nor months or days.

**Comment by WhiteKarma** [comment]
Thank you, can you paste a screen shot here https://snag.gy/ and post the resulting link to make available the image of the situation?

Thank you!!!

**Comment by WhiteKarma** [comment]
Thank you, can you please attach a screenshot, so that we can figure out how to solve it?
To attach a file drag it to a comment you are writing or select the file using the link on the lower area of the comment window.

Thank you!!!

**Comment by LVS04** [comment]
Here it is body: https://snag.gy/Y4QbxB.jpg

 

 

De : WhiteKarma [mailto:notifications@github.com] 
Envoyé : mardi 27 septembre 2016 12:07
À : WhiteKarma/NalandaERP <NalandaERP@noreply.github.com>
Cc : LVS04 <lvs04@yahoo.fr>; Author <author@noreply.github.com>
Objet : Re: [WhiteKarma/NalandaERP] Calendar button unusable (#11)

 

Thank you, can you paste a screen shot here https://snag.gy/ and post the resulting link to make available the image of the situation?

Thank you!!!

**Comment by LVS04** [comment]
Here the screen shot !!

 

De : WhiteKarma [mailto:notifications@github.com] 
Envoyé : mardi 27 septembre 2016 12:27
À : WhiteKarma/NalandaERP <NalandaERP@noreply.github.com>
Cc : LVS04 <lvs04@yahoo.fr>; Author <author@noreply.github.com>
Objet : Re: [WhiteKarma/NalandaERP] Calendar button unusable (#11)

 

Thank you, can you please attach a screenshot, so that we can figure out how to solve it?
To attach a file drag it to a comment you are writing or select the file using the link on the lower area of the comment window.

Thank you!!!

**Comment by WhiteKarma** [comment]
Sorry, both screen shots are inaccessible. Can you attach the screenshot directly on a comment to this issue on the site? The link to this issue is https://github.com/WhiteKarma/NalandaERP/issues/11
To attach a file drag it to a comment you are writing or select the file using the link on the lower area of the comment window.

Thank you!!!

**Comment by LVS04** [comment]
Done !

 

De : WhiteKarma [mailto:notifications@github.com] 
Envoyé : mardi 27 septembre 2016 12:40
À : WhiteKarma/NalandaERP <NalandaERP@noreply.github.com>
Cc : LVS04 <lvs04@yahoo.fr>; Author <author@noreply.github.com>
Objet : Re: [WhiteKarma/NalandaERP] Calendar button unusable (#11)

 

Sorry, both screen shots are inaccessible. Can you attach the screenshot directly on a comment to this issue on the site? The link to this issue is #11 <https://github.com/WhiteKarma/NalandaERP/issues/11> 
To attach a file drag it to a comment you are writing or select the file using the link on the lower area of the comment window.

Thank you!!!

**Comment by WhiteKarma** [comment]
Please check this link so that you can see what i see https://github.com/WhiteKarma/NalandaERP/issues/11

**Comment by LVS04** [comment]
I try again....
![calendar screen shot](https://cloud.githubusercontent.com/assets/22444859/18871874/c28e01f2-84b7-11e6-9342-54e7491dbe9f.jpg)

**Comment by WhiteKarma** [comment]
Perfect!!!
Just so you know, i've always seen it like this:
![calendar](https://cloud.githubusercontent.com/assets/17479531/18872141/2ef4fa5c-84b9-11e6-94bd-f1d906d3ccab.png)

This is a third party component, i will check if i can force the position somehow. Good issue!

Thank you!!!

**Comment by WhiteKarma** [comment]
I made some changes and already published, can you check if it is OK?

Thank you!!!

**Comment by LVS04** [comment]
Very good my friend!! That's perfect!! You can close the topic!!

**Comment by WhiteKarma** [comment]
AHAHAHAHAHA, thank you. I am here to help!!! 👍
