### ISSUE TITLE
Neighborhood

### ISSUE THREAD

**Issue by LVS04** [WhiteKarma/NalandaERP#14]
Neighborhood (Main / Adress): don't know what it is??? Is it useful??? :-)

**Comment by WhiteKarma** [comment]
Yes, please check almost complete WhiteKarma's address attached on this post.

Thank you!!!
![neighborhood](https://cloud.githubusercontent.com/assets/17479531/18869484/d50937f8-84ac-11e6-82e4-9918469c3e42.png)

**Comment by LVS04** [comment]
I think it concerns only the Portuguese…. :)

 

De : WhiteKarma [mailto:notifications@github.com] 
Envoyé : mardi 27 septembre 2016 12:21
À : WhiteKarma/NalandaERP <NalandaERP@noreply.github.com>
Cc : LVS04 <lvs04@yahoo.fr>; Author <author@noreply.github.com>
Objet : Re: [WhiteKarma/NalandaERP] Neighborhood (#14)

 

Yes, please check almost complete WhiteKarma's address attached on this post.

Thank you!!!
 <https://cloud.githubusercontent.com/assets/17479531/18869484/d50937f8-84ac-11e6-82e4-9918469c3e42.png>

**Comment by LVS04** [comment]
??? no comprendo… :)

 

De : WhiteKarma [mailto:notifications@github.com] 
Envoyé : mardi 27 septembre 2016 12:21
À : WhiteKarma/NalandaERP <NalandaERP@noreply.github.com>
Cc : LVS04 <lvs04@yahoo.fr>; Author <author@noreply.github.com>
Objet : Re: [WhiteKarma/NalandaERP] Neighborhood (#14)

 

Yes, please check almost complete WhiteKarma's address attached on this post.

Thank you!!!
 <https://cloud.githubusercontent.com/assets/17479531/18869484/d50937f8-84ac-11e6-82e4-9918469c3e42.png>

**Comment by WhiteKarma** [comment]
AHAHAHAHAHAHAHA!!!

Just to inform, the source of the structure of the fields was google contacts, because we are going to interface with it to post some of the contact information to relevant google e-mail accounts. It is part of the features.

You can comment directly on the website on the corresponding window rather than replying to the e-mail if you like.

Thank you!!!
