### ISSUE TITLE
Tags removale

### ISSUE THREAD

**Issue by LVS04** [WhiteKarma/NalandaERP#19]
Hell Pedro,
There is a little cross in the tags square typical to remove it but it is not working. I have understood that you can remove by double clicking, no problem, but that cross should work or be removed.
Thanks bro!!

**Comment by LVS04** [comment]
I mean... Hello Pedro!! :-)

**Comment by WhiteKarma** [comment]
Hehehehe, hello @LVS04, you are right, the normal behavior of the 'X' besides marking the spot, is that, however the control i am using has two modes: Read-only which is the one we are using now, or in Edit mode which enables the use of that button but also direct typing to create tags, which in our case is even less desirable than not having the close button working. I am working on a Tag creation feature that is going to be a separate menu option, to be used later with restricted access. The enabling of the cross while in Read-Only mode, will need me to tweak the control itself to change its default behavior, it will take time to dig into the code and find a solution for it. Maybe another solution would be to simply enable the double click on the chosen tags to remove them, what do you think?

Thank you very much

**Comment by LVS04** [comment]
Hello White Karma !!

Yes I agree on the constraints. The best is to remove the ‘X’ and keep the double click to remove.

Thank you!

 

De : WhiteKarma [mailto:notifications@github.com] 
Envoyé : mercredi 12 octobre 2016 11:32
À : WhiteKarma/NalandaERP <NalandaERP@noreply.github.com>
Cc : LVS04 <lvs04@yahoo.fr>; Mention <mention@noreply.github.com>
Objet : Re: [WhiteKarma/NalandaERP] Tags removale (#19)

 

Hehehehe, hello @LVS04 <https://github.com/LVS04> , you are right, the normal behavior of the 'X' besides marking the spot, is that, however the control i am using has two modes: Read-only which is the one we are using now, or in Edit mode which enables the use of that button but also direct typing to create tags, which in our case is even less desirable than not having the close button working. I am working on a Tag creation feature that is going to be a separate menu option, to be used later with restricted access. The enabling of the cross while in Read-Only mode, will need me to tweak the control itself to change its default behavior, it will take time to dig into the code and find a solution for it. Maybe another solution would be to simply enable the double click on the chosen tags to remove them, what do you think?

Thank you very much

**Comment by WhiteKarma** [comment]
The Tags can be removed now on the x like it is normal procedure, also changed the double-click to add by single-click because on some tablets, double click has other default functionality.

Thank you very much!
