### ISSUE TITLE
check: website validation

### ISSUE THREAD

**Issue by palbert1976** [WhiteKarma/NalandaERP#2]
Put in both a structurally complete but non-existing web address as well as an accurate web address and both generated the error message please enter a correct url--it accepts the record and highlights the field, but perhaps we need a sample model of what it is checking for http  www ect.

**Comment by WhiteKarma** [comment]
Hello Pete, i am not sure i understood your point. The internal url, is not working on the document. I sent a correction to the test team and also changed the document, it is **http://test-erp./**  

Thank you!

**Comment by WhiteKarma** [comment]
The link on the documentation was not working. The changed link was sent to everyone, so i am closing this issue.

Thank you!!!
