### ISSUE TITLE
Identification: Default dates

### ISSUE THREAD

**Issue by palbert1976** [WhiteKarma/NalandaERP#3]
the default date of the calendar comes up ten years ago (2006) for the issue date and since most passport are for ten years this date would have already expired or expires today

      (Consider five years back as the default start date)

the default date of the calendar comes up ten years ago (2006) for the expiration date and which means you have to go ten years forward even before you get to the starting point of an "unexpired" document--
    (Set default date to "today" )

It may be helpful to add a screen instruction to click on the date in the calendar to get more calendar navigation controls

**Comment by WhiteKarma** [comment]
Please note that you can click on the input field box and type directly the date and press enter to be accepted. The default date will be changed to 5 year back, has you suggested. It is a good idea.

**Comment by WhiteKarma** [comment]
DONE!!!
Default issue date changed to five years back and expiration to today for new contacts.
I am closing the issue. As soon as a new deployment is available, you will be able to check.

Thank you very much!!!
